### ISSUE TITLE
Problem with states which have the same type

### ISSUE THREAD

**Issue by GabrielHuettenberger** [FlexBE/flexbe_app#15]
When having two state types with identical names in different state packages, the App only shows one of the two types twice when using the Add State feature. Which type is shown twice seems to change randomly on App restart.
![state_type1](https://user-images.githubusercontent.com/919186/40049554-5bd84dde-5835-11e8-9f2f-f560c90c391f.png)
![state_types2](https://user-images.githubusercontent.com/919186/40049557-5db5ad40-5835-11e8-9a2d-af09b3ad4e67.png)

**Comment by pschillinger** [comment]
Thanks for reporting, I will look into it.

Independent of this, I would suggest to give rather specific names to states and make sure that states are indeed different in the sense that they are more than just two different hardcoded parametrizations of the same functionality. But of course, the issue you reported needs to be fixed.

**Comment by pschillinger** [comment]
This problem should be fixed now by the above referenced commit.

In short:

* Duplicate state class names are now correctly handled within the app.
* For generated code, duplicate state classes are imported with according aliases. This enables to correctly load the respective state class when loading a behavior in the app.
* There is a new entry in the settings to do the above explicitly for all state classes even if unique.
