### ISSUE TITLE
Clicking New Behavior button does not set `rosnode_name`, but appears to.

### ISSUE THREAD

**Issue by dustingooding** [FlexBE/flexbe_app#24]
When you click the `New Behavior` button, all the Behavior fields are reset to empty values, but the `Package` dropdown in the `Dashboard` view is populated with the default behavior package name.  If you assume it's set (as it appears to be), then continue defining the rest of the required fields/states, then click the `Save Behavior` button, you get what appears to be a successful action (no errors, etc).  You also get so saved file!  I injected some debug-style printing and found the following in the `updateManualSelections` call that is reached by the `saveBehaviorClicked` method:

```
# my debug output added
	this.updateManualSections = function(callback) {
		var names = Behavior.createNames();
		T.logError(">>> BEHAVIOR NAMES CREATED");
		T.logError(">>> BEHAVIOR PKG: " + names.rosnode_name);
		T.logError(">>> BEHAVIOR NAME: " + names.file_name);
		T.logError(">>> BEHAVIOR NAME_TMP: " + names.file_name_tmp);
```

which results in:

```
>>> BEHAVIOR NAMES CREATED
>>> BEHAVIOR PKG: 
>>> BEHAVIOR NAME: asdf_sm.py
>>> BEHAVIOR_NAME_TMP: adsf_sm_tmp.py
```

If I go back to the `Dashboard` and manually click and select the package name in the `Package` dropdown, followed by the `Save Behavior` button again, the `rosnode_name` value is set and the save is successful.

Proposals:

1) Automatically set `rosnode_name` to the currently selected `Package`, even after a `New Behavior` is clicked.
2) Add an empty field to the `Package` dropdown to force a selection.  (This is probably easier and more correct.)

**Comment by pschillinger** [comment]
Fixed by @dustingooding in the commit referenced above. Thank you!
