### ISSUE TITLE
Container with the same Key for input and output

### ISSUE THREAD

**Issue by AARobotics** [FlexBE/flexbe_app#26]
Is it possible to have a container that gets an input key, process it and set it as an output key?
The idea is having number of containers processing the same parameter and passing it between them.
Process A edits a key, passes it to process B (in some cases to C),  and then next time A is reached it will use again the same key and edit it.

Thank you for the help.

**Comment by pschillinger** [comment]
Yes, this is totally possible and quite common. Simply define an input key and an output key for the respective container and map them to the same name (in the properties-panel of the container in the editor).
