### ISSUE TITLE
Explicit state package feature bug

### ISSUE THREAD

**Issue by RhysMcK** [FlexBE/flexbe_app#30]
I am encountering an issue when i save my Flexbe behaviors with the latest release. I believe it has stemmed from the changes made in this commit, https://github.com/FlexBE/flexbe_app/commit/e4b90f3a71d03e26bf5b72cdd93f6ff1e22b2013 . When behaviors are saved in the app it gives imported behaviors aliases which are not handled  (i.e renamed) in the the rest of that behaviors file.
![screenshot from 2019-01-17 15-17-22](https://user-images.githubusercontent.com/15118900/51297185-05a47e80-1a6b-11e9-889a-e44ef697fc59.png)

Was the idea to just give aliases to the imported **states** only? I notice when you turn off the explicit state package feature in the settings it has no effect on the behavior imports, they are still given an alias. 

Cheers!

**Comment by ffriese** [comment]
I had the same issue and fixed it in my fork with 2afa637417c10fdbc9216113f2aac8b80800ab94.
I have not yet gotten around to make a pull request out of it, and I was not sure if I had found all relevant code sections, but it seems to have worked for me.

**Comment by cjue** [comment]
I can also confirm this issue. Since 2.0.11 we get errors when using nested behaviors because of the mentioned renaming.

**Comment by pschillinger** [comment]
Thank you for reporting! Yes, the intent was to ignore behaviors, but a type check was missing. This is fixed now.
