### ISSUE TITLE
fails to compile

### ISSUE THREAD

**Issue by GalMoore** [FlexBE/flexbe_app#31]
**Downloading nwjs... CMake Error at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):   execute_process(/home/gal/flexBE_ws/src/flexbe_app/bin/nwjs_install)   returned error code 18 Call Stack (most recent call first):   flexbe_app/CMakeLists.txt:36 (safe_execute_process) during compilation**

Could it be cause I'm running Ubuntu 18.04 with ROS Melodic?

**Comment by GalMoore** [comment]
any idea why this happens? server maybe?

**Comment by pschillinger** [comment]
Can you try to run

    rosrun flexbe_app nwjs_install

seperately? Does it fail as well? If yes, what's the error there?

Ubuntu 18.04 with melodic should be fine, I'm using the same at the moment.

**Comment by GalMoore** [comment]
Somehow got it to work on melodic and kinetic - thanks. I should have a few more installs to go on new machines so if I have the same issue I'll try your recommendation.
