### ISSUE TITLE
The States in the Concurrenncy Container does not Run Parallally as Intended.

### ISSUE THREAD

**Issue by paulsebastian97** [FlexBE/flexbe_app#44]
I have created a flexbe behavior to test the working of concurrency container. The concurrency container contains 3 states which should run parallelly. Each of these 3 states basically publishes a unique string to 3 different topics. The value published by the topic is printed using "rostopic echo" ROS command. But when I run the behavior, the 3 concurrency states do not print  the strings simultaneously instead prints the strings one after another. This is not how the parallel states should run in a concurrency container. Instead, all the 3 strings should be printed at once. I have attached my flexbe behavior graph and code.

The below two images show the behavior flow.
![behavior_flow](https://user-images.githubusercontent.com/44846728/68120117-941abb80-ff2a-11e9-9e4d-7bc1bbd1b23a.png)

![3_states_inside_concurrency_container](https://user-images.githubusercontent.com/44846728/68120141-a0067d80-ff2a-11e9-9a6f-176da1e0f7c9.png)

I have attached the behavior and the code for the individual states below.
[flexbe_behavior_and_states.tar.gz](https://github.com/FlexBE/flexbe_app/files/3803913/flexbe_behavior_and_states.tar.gz)

**Comment by pschillinger** [comment]
Closing in favor of team-vigir/flexbe_behavior_engine#84
