### ISSUE TITLE
Extreme CPU load by Python processes after shutdown of FlexBE app

### ISSUE THREAD

**Issue by joostvanstuijvenberg** [FlexBE/flexbe_app#56]
While using the FlexBE app through `roslaunch flexbe_app flexbe_ocs.launch`, I can see in output of **top** that a bunch of Python-processes are running (probably 10 or something). When I close the app these processes start to consume way more CPU cycles than before (on average 0,3 while using the app, around 75 right after shutdown.

![Screenshot from 2020-03-06 09-56-53](https://user-images.githubusercontent.com/22455304/76068544-9ef56380-5f91-11ea-8e07-6b74fa397de5.png)
![Screenshot from 2020-03-06 09-57-10](https://user-images.githubusercontent.com/22455304/76068545-9f8dfa00-5f91-11ea-8aca-f029642cc84b.png)

I checked out the "develop"-branch of flexbe_app, rebuilt everything and this phenomenon didn't show up.

**Comment by pschillinger** [comment]
Thanks for updating! I was about to ask which branch you used because the issue should be fixed by [this commit](https://github.com/FlexBE/flexbe_app/commit/a927e1d8751825a4c3f031b2d9d6f63a4fda435b) on develop. I plan to merge it into master during the next days.

**Comment by joostvanstuijvenberg** [comment]
Great! Keep up the good work.

In the mean time I'll have some reading material that might somehow feel familiar to you :-)

Cheers,
Joost

**Comment by pschillinger** [comment]
Released with 2.2.4
