### ISSUE TITLE
repeated behavior and package display

### ISSUE THREAD

**Issue by zengxiaolei** [FlexBE/flexbe_app#59]
Hi, 
first, what I use is ROS melodic in Ubuntu18.04,  flexbe_app develop branch (latest) and flexbe_behavior_engine  develop branch (latest).  When I load behaviors in flexbe APP, all available behaviors and the available package display twice as shown in Fig. 1.
![app-load](https://user-images.githubusercontent.com/34747839/77023095-56449e00-69c6-11ea-93e9-def3744811e7.png)
Fig.1

The states display are normal.The following are references that may be useful.
![behavior-src](https://user-images.githubusercontent.com/34747839/77023215-a0c61a80-69c6-11ea-9c9b-b70fa811a353.png)
Fig.2

![menifest](https://user-images.githubusercontent.com/34747839/77023221-a4f23800-69c6-11ea-8cff-57051d977b33.png)
Fig. 3

More information can be provided if needed.

By the way, if there any command to check available behavior name without launch flexbe app, so that certain behavior can be run by command?

**Comment by pschillinger** [comment]
This might be an issue with the ROS package cache that the FlexBE App uses internally to not check all packages for states and behaviors during every start. Can you go to the "Configuration" page and press "Force Discover"? Does this fix it? It might take a moment to refresh the cache.

Regarding you question, did you check [this tutorial](http://wiki.ros.org/flexbe/Tutorials/Running%20Behaviors%20Without%20Operator)? If this does not provide the function you need, what exactly would you need? In addition to what is written there, the Python API exists for looking up behaviors by name, but there is no command-line script for it (yet).

**Comment by zengxiaolei** [comment]
"Force Discover" works! Thanks a lot.
