### ISSUE TITLE
Behavior parameter's default value is not validating

### ISSUE THREAD

**Issue by alireza-hosseini** [FlexBE/flexbe_app#6]
Another issue about behavior parameter is that you can set any default value regardless of whether it is in the MIN and MAX bounds or not.

**Comment by pschillinger** [comment]
Can you provide additional details or give an example where this fails? I am not able to reproduce this issue.

**Comment by pschillinger** [comment]
Able to replicate: For float values, only the int conversion is used for comparison. Will be fixed soon.
