### ISSUE TITLE
Flexbe_app does not see code changes on states since 2.3.0

### ISSUE THREAD

**Issue by tremblay0934** [FlexBE/flexbe_app#69]
Saving in the IDE does not update the code for the runtime. I've tested and noticed that changing the 'outcomes' variables in the constructor of the EventState parent class will be noticed correctly by the flexbe_app and the GUI blocks will now show the new outcomes, however, adding, for example, logging messages after that does not work. 

What i mean by "does not work" is that the state is executed, but the logging never happens in the runtime/Flexbe_app console. Only shutting down roslaunch and restartind my nodes works.

This used to work in flexbe 2.2.4. Any idea what might have caused it? i've looked at the commits but don't think any of them had something to do with this problem.

**Comment by pschillinger** [comment]
I'm also not aware of any changes I did in the flexbe_app code that could cause such a behavior. Given that a change in outcomes is updated correctly, I think the state update on the GUI side works correctly as far as I understand you.

The logging messages are a different topic. The code that is executed does not need to be updated by the GUI, this is just loaded by the onboard engine. I assume that is the same to which you refer in team-vigir/flexbe_behavior_engine#135, so let's head there to talk about it. Or is there something else related to the GUI?
