### ISSUE TITLE
Installed behavior packages in workspace

### ISSUE THREAD

**Issue by GabrielHuettenberger** [FlexBE/flexbe_app#75]
We noticed a problem when working with behavior packages which are both installed and available in the workspace. The expected behavior for these packages would be that the version of the package in the workspace has a higher priority and should be used.

What happens is that for certain FlexBE functionality like opening the behavior code from the app directly the workspace file will be opened but on the other hand it is not possible to save any changes made in the behavior through the FlexBE app since we get the error that the behavior is read only which points to FlexBE trying to use the installed package.
It is also not possible to create new behaviors in a workspace package when the package is installed and we get the same error message.
![image](https://user-images.githubusercontent.com/919186/116037306-30c5a180-a668-11eb-80b5-1f927c9d0a7f.png)

**Comment by dcconner** [comment]
Is PR #76 intended to address this issue ?

**Comment by dcconner** [comment]
See also #81
