### ISSUE TITLE
Nested concurrent containers get stuck

### ISSUE THREAD

**Issue by Combinacijus** [FlexBE/flexbe_app#79]
Can't get concurrent container working inside another concurrent container. In the child container it seem that only first state executed and it gets stuck on the second one independent on what state it is

Here's minimal behaviour to reproduce error (ROS1):
https://gist.github.com/Combinacijus/e46ac54c6cb8e5b0bb4ab22b17e17324

It's structure (ConcurentContainer = CC):
```
 Start
  |
  \/
 CC1
  |
  ----------------------------
  |                          |
  \/                         \/
 CC2                       LOG1
  |
  \/
 LOG2
```
![image](https://user-images.githubusercontent.com/16375702/153731357-3840050c-a205-4587-a1df-d13aef5bccbb.png)

![image](https://user-images.githubusercontent.com/16375702/153731362-8cc547e6-3c15-44e5-8533-464f52e082ea.png)

LOG1:  ( Log1  -> Wait1 -> (Repeat LOG1))
![image](https://user-images.githubusercontent.com/16375702/153731365-c5ef2246-0e5c-465f-baaf-c0cc5679e73d.png)

LOG2_2:  ( Log2  -> Log2_2  ->  Wait2 -> (Repeat LOG2))
![image](https://user-images.githubusercontent.com/16375702/153731369-109bd882-c018-41c4-bb03-4256fdf22fab.png)

LOG1 state log repeatedly as expected.

## Problem
LOG2 executes only first state (Log2) and gets stuck on Log2_2 (or any other state which is second). And it's so stuck that outcome can't be forced. Also to stop all execution I have to restart whole behaviour engine

Output:
![image](https://user-images.githubusercontent.com/16375702/153731446-8eaa1e80-8f1a-4ccc-874d-65d3ddc814eb.png)

Expected output:
```
2
1
2
1
```

**Comment by RhysMcK** [comment]
I can confirm this is an issue. I suspect its an issue in the https://github.com/team-vigir/flexbe_behavior_engine. Im using the latest release 1.3.1. I did noticed that they have moved the repo to https://github.com/FlexBE/flexbe_behavior_engine/tree/main, however there doesn't seem to be any changes better the two... yet.

**Comment by dcconner** [comment]
Presume this discussion is on the ROS 1 version. 

I'll be porting some recent develop changes from team-vigir side in the next couple of weeks over to here and updating the main branch.

**Comment by dcconner** [comment]
Note changes to Noetic version are posted, and a brand new ros2-devel & humble version are pushed.  I will look into this a bit more and try to duplicate, but I would appreciate any testing with the new versions.  I'm focused on ROS 2 at the moment, so I won't be doing further testing on Noetic except for bug fixes.

**Comment by dcconner** [comment]
Closing this and referring discussion to #88
