### ISSUE TITLE
Statemachine Editor: Selecting a state transition net and then pressing `Esc` key causes the state transition net to disappear

### ISSUE THREAD

**Issue by josephcoombe** [FlexBE/flexbe_app#9]
In the picture below, the 'failure' outcome of the InitializeLeg state is connected to the state machine's (sm) 'failed' outcome:
![screenshot1](https://user-images.githubusercontent.com/12258096/33677937-0748cd76-da80-11e7-8d0e-ad49f1083ce7.png)

However, that connection was a mistake. I don't want to exit the sm if InitializeLeg state returns a 'failure' outcome, but I'm not sure where it should go. I want to move the 'failure' outcome back to InitializeLeg state like 'shutdown', so I select the 'failure' net.
![screenshot2](https://user-images.githubusercontent.com/12258096/33677936-0736cebe-da80-11e7-8dd5-861b78a92b58.png)

and press 'Esc'. This causes InitializeLeg's 'failure' outcome net to disappear. Now the only way to get it back is to restart the FlexBE app, destroying any unsaved work.
![screenshot3](https://user-images.githubusercontent.com/12258096/33677935-0727d832-da80-11e7-99b9-ceab946c55e7.png)

---
The workaround is to connect outcome nets somewhere else _(e.g. the origin state)_; however, it would be better if there were a way to move the outcome back inside the state box to prevent confusion between outcome nets that supposed to loop back and outcome nets that are just there temporarily.
![screenshot4](https://user-images.githubusercontent.com/12258096/33677934-071a109e-da80-11e7-847a-610838d1ea26.png)

**Comment by pschillinger** [comment]
Thank you for reporting this bug! Yes, the Esc key is supposed to correctly
reset a transition and of course it should never be required to restart the
App. I will look into this.

**Comment by pschillinger** [comment]
I was able to reproduce this problem for cancelling a transition with a container outcome as target. This is fixed now on develop.

The key bindings are now as follows:

* `Escape`: Reset the transition, i.e., snap back at the target before touching it (same behavior as intended before)
* `Delete`: Remove the transition and list it again as unconnected outcome (new key binding)

**Comment by josephcoombe** [comment]
Works exactly as I'd expect. Thank you!
